version: "3.8"

services:
  palace:
    image: node:18
    volumes:
      - .:/palace
    working_dir: /palace
    command: yarn run dev
    ports:
      - "3000:3000"

  deps:
    image: node:18
    volumes:
      - .:/palace
    working_dir: /palace
    command: yarn install
